# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(967, 398)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 20, 111, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(500, 220, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(500, 80, 91, 16))
        self.label_5.setObjectName("label_5")
        self.txt_plantext = QtWidgets.QTextEdit(Dialog)
        self.txt_plantext.setGeometry(QtCore.QRect(100, 70, 341, 111))
        self.txt_plantext.setObjectName("txt_plantext")
        self.txt_ciphertext = QtWidgets.QTextEdit(Dialog)
        self.txt_ciphertext.setGeometry(QtCore.QRect(100, 210, 341, 111))
        self.txt_ciphertext.setObjectName("txt_ciphertext")
        self.txt_information = QtWidgets.QTextEdit(Dialog)
        self.txt_information.setGeometry(QtCore.QRect(570, 70, 341, 111))
        self.txt_information.setObjectName("txt_information")
        self.txt_signature = QtWidgets.QTextEdit(Dialog)
        self.txt_signature.setGeometry(QtCore.QRect(570, 210, 341, 111))
        self.txt_signature.setObjectName("txt_signature")
        self.btn_encrypt = QtWidgets.QPushButton(Dialog)
        self.btn_encrypt.setGeometry(QtCore.QRect(90, 340, 93, 28))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(Dialog)
        self.btn_decrypt.setGeometry(QtCore.QRect(280, 340, 93, 28))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sigh = QtWidgets.QPushButton(Dialog)
        self.btn_sigh.setGeometry(QtCore.QRect(590, 340, 93, 28))
        self.btn_sigh.setObjectName("btn_sigh")
        self.btn_verity = QtWidgets.QPushButton(Dialog)
        self.btn_verity.setGeometry(QtCore.QRect(780, 340, 93, 28))
        self.btn_verity.setObjectName("btn_verity")
        self.btn_generatekeys = QtWidgets.QPushButton(Dialog)
        self.btn_generatekeys.setGeometry(QtCore.QRect(520, 30, 141, 28))
        self.btn_generatekeys.setObjectName("btn_generatekeys")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "RSA Cipher"))
        self.label_2.setText(_translate("Dialog", "Plan Text:"))
        self.label_3.setText(_translate("Dialog", "Cipher Text:"))
        self.label_4.setText(_translate("Dialog", "Signature: "))
        self.label_5.setText(_translate("Dialog", "Infomation: "))
        self.btn_encrypt.setText(_translate("Dialog", "Encrypt"))
        self.btn_decrypt.setText(_translate("Dialog", "Decrypt"))
        self.btn_sigh.setText(_translate("Dialog", "Sign"))
        self.btn_verity.setText(_translate("Dialog", "Verity"))
        self.btn_generatekeys.setText(_translate("Dialog", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
