# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PUGIN_PATH'] = "../platform"

class Ui_ECCCipher(object):
    def setupUi(self, ECCCipher):
        ECCCipher.setObjectName("ECCCipher")
        ECCCipher.resize(400, 300)
        self.label = QtWidgets.QLabel(ECCCipher)
        self.label.setGeometry(QtCore.QRect(100, 10, 121, 16))
        self.label.setObjectName("label")
        self.btn_sign = QtWidgets.QPushButton(ECCCipher)
        self.btn_sign.setGeometry(QtCore.QRect(50, 260, 93, 28))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(ECCCipher)
        self.btn_verify.setGeometry(QtCore.QRect(210, 260, 93, 28))
        self.btn_verify.setObjectName("btn_verity")
        self.btn_generatekeys = QtWidgets.QPushButton(ECCCipher)
        self.btn_generatekeys.setGeometry(QtCore.QRect(200, 10, 93, 28))
        self.btn_generatekeys.setObjectName("btn_generatekeys")
        self.label_2 = QtWidgets.QLabel(ECCCipher)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ECCCipher)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 71, 16))
        self.label_3.setObjectName("label_3")
        self.txt_information = QtWidgets.QTextEdit(ECCCipher)
        self.txt_information.setGeometry(QtCore.QRect(90, 40, 301, 91))
        self.txt_information.setObjectName("txt_information")
        self.txt_signature = QtWidgets.QTextEdit(ECCCipher)
        self.txt_signature.setGeometry(QtCore.QRect(90, 150, 301, 91))
        self.txt_signature.setObjectName("txt_signature")

        self.retranslateUi(ECCCipher)
        QtCore.QMetaObject.connectSlotsByName(ECCCipher)

    def retranslateUi(self, ECCCipher):
        _translate = QtCore.QCoreApplication.translate
        ECCCipher.setWindowTitle(_translate("ECCCipher", "Dialog"))
        self.label.setText(_translate("ECCCipher", "ECC Cipher"))
        self.btn_sign.setText(_translate("ECCCipher", "Sign"))
        self.btn_verify.setText(_translate("ECCCipher", "Verity"))
        self.btn_generatekeys.setText(_translate("ECCCipher", "Generate Keys"))
        self.label_2.setText(_translate("ECCCipher", "Infomation: "))
        self.label_3.setText(_translate("ECCCipher", "Signature: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ECCCipher = QtWidgets.QDialog()
    ui = Ui_ECCCipher()
    ui.setupUi(ECCCipher)
    ECCCipher.show()
    sys.exit(app.exec_())
